MaskedPerson gaogui = new MaskedPerson("Gao Gui")
MaskedPerson yuchen = new MaskedPerson("Yu Chen")
MaskedPerson gabriel = new MaskedPerson("Gabriel")
MaskedPerson yuze = new MaskedPerson("Yuze")
MaskedPerson cheehong = new MaskedPerson("Chee Hong")
gaogui.infectWith(List.of(new AlphaCoronavirus(0.99)), 0.61)
Arrays.toString(gaogui.transmit(1).toArray())
Arrays.toString(gaogui.transmit(0.99).toArray())
Arrays.toString(gaogui.transmit(0.6).toArray())
gaogui.infectWith(List.of(new SARS_CoV_2(1)), 0.6)
Arrays.toString(gaogui.transmit(1).toArray())
Arrays.toString(gaogui.transmit(0.99).toArray())
Arrays.toString(gaogui.transmit(0.6).toArray())
yuchen.infectWith(List.of(new SARS_CoV_2(1), new AlphaCoronavirus(0.5)), 0.7);
Arrays.toString(yuchen.transmit(0.61).toArray())
Arrays.toString(yuchen.transmit(0.6).toArray())
gabriel.infectWith(List.of(new AlphaCoronavirus(0.5)), 0.61)
RandomNumberGenerator.reset()
Contact c = new Contact(gabriel, yuze, 1)
c = new Contact(gabriel, cheehong, 1)
c = new Contact(yuze, cheehong, 1)
Arrays.toString(gabriel.transmit(0.61).toArray())
Arrays.toString(gabriel.transmit(0.6).toArray())
Arrays.toString(yuze.transmit(0.61).toArray())
Arrays.toString(yuze.transmit(0.6).toArray())
Arrays.toString(cheehong.transmit(0.61).toArray())
Arrays.toString(cheehong.transmit(0.6).toArray())
/exit
