Person mingsoon = new Person("Ming Soon")
Person longThePerson = new Person("Long")
Person guoyu = new Person("Guoyu")
Person rishabh = new Person("Rishabh")
Person nigel = new Person("Nigel")
Location l = new Location("LT19")
Arrays.toString(l.getOccupants().toArray())
l.accept(mingsoon)
l.accept(longThePerson)
Arrays.toString(l.getOccupants().toArray())
l.accept(guoyu)
l.remove(mingsoon)
Arrays.toString(l.getOccupants().toArray())
l.accept(rishabh)
l.accept(nigel)
Arrays.toString(l.getOccupants().toArray())
l.remove(longThePerson)
l.remove(guoyu)
l.remove(rishabh)
l.remove(nigel)
Arrays.toString(l.getOccupants().toArray())
/exit
